language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
dist: xenial

install:
 - pip install .
 - pip install -r requirements.txt

script: nosetests --with-coverage --nologcapture tests

after_success:
 - coveralls
