language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "nightly"

install:
 - pip install .
 - pip install -r requirements.txt

script: nosetests --with-coverage --nologcapture tests

after_success:
 - coverage combine
 - coveralls
